### ISSUE TITLE
Use user home path `HOME_PATH` or `TEMP_PATH` instead of somewhere inside the Ruby gem directories

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-importer#43]
https://github.com/metanorma/bipm-data-importer/blob/d97f39881dd39c43828addd4d3e4e26273c9c119/lib/bipm/data/outcomes.rb#L8-L10

In some environments like Tebako, the Ruby runtime and its libraries are located in a read-only partition. We have to use the user home path or a temp path for dynamically downloaded files.

**Comment by webdev778** [comment]
Duplicate of #38

The logic as of now is that:

1. If the directory isn't writable, it falls back to homedir: https://github.com/metanorma/bipm-data-importer/blob/d97f39881dd39c43828addd4d3e4e26273c9c119/lib/bipm/data/outcomes.rb#L46
2. Otherwise, it's possible to override a path with an attr_writer provided. Since the API is for a programmer to browse the dataset, he can simply use `Bipm::Data::Outcomes.file_path = "/tmp/my_bipm_data"` before executing the rest

**Comment by ronaldtse** [comment]
Thank you for the clarification, indeed it would work. Closing.
